test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>


# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1


#   bucket: your_own_bucket
google_dev:
  service: GCS
  project: PropGrid
  credentials: <%= Rails.root.join("config/secrets/test.json") %>
  bucket: leases



google:
  service: GCS
  credentials:
    type: service_account
    project_id: ENV['GCP_PROJECT_ID']
    private_key_id: ENV['GCP_PRIVATE_KEY_ID']
    private_key: ENV['GCP_PRIVATE_KEY']
    client_email: ENV['GCP_CLIENT_EMAIL']
    client_id: ENV['GCP_CLIENT_ID']
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://accounts.google.com/o/oauth2/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/starting-account-lfkdsx7ugofc%40propgrid-1584978193000.iam.gserviceaccount.com 
  project: PropGrid
  bucket: leases
#google:
#  service: GCS
#  credentials:
#    type: "service_account"
#    project_id: ENV[GCP_PROJECT_ID]
#    private_key_id: ENV[GCP_PROJECT_ID]
#    private_key: ENV[GCP_PRIVATE_KEY]
#    client_email: ENV[GCP_CLIENT_EMAIL]
#    client_id: ENV[GCP_CLIENT_ID]
#    auth_uri: ENV[GCP_AUTH_URI]
#    token_uri: ENV[GCP_TOKEN_URI]
#    auth_provider_x509_cert_url: ENV[GCP_AUTH_PROVIDER_X509_CERT_URL]
#    client_x509_cert_url: ENV[GCP_CLIENT_X509_CERT_URL]
#  project: ""
#  bucket: "leases"

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
